# Generated by Django 3.0.4 on 2020-03-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deck',
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='question',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
