# Generated by Django 3.0.4 on 2020-03-11 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_auto_20200311_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='answer',
            new_name='back',
        ),
        migrations.RenameField(
            model_name='flashcard',
            old_name='question',
            new_name='front',
        ),
    ]
